<?php

// pulling var from new admin form (test)
$adminFormTest = variable_get('library_hours_orgs', '');

// sets global var $scrcToday with open hours for current day: e.g. "Monday Hours: 8am - 10pm" (hours set on in fields on page /scrc/hours-input)

// suggested use would be to call the var in a node or block as needed like this:
// $todayString = variable_get('scrcToday','');
// echo "<p>" . $todayString . "</p>";


//$testDate = '2014-01-12';
//$weekDay = date('l', strtotime( $testDate));

//$deptName= ""; //global variables
$constant = ""; //holds the names of different departments - global varible

$depts = array("scrc","grc","test1","test2"); // <--- Include the new department in this array

// this function is used to set the global array - [constant]
// tried to set it without a function but then it is not detected in hook functions.
 
function setDept($depts)
{
  $GLOBALS['constant']= $depts;
}

// setting the global variable [constant] which contains same value as depts
setDept($depts);

// Calling the setTime function for each department
foreach($depts as $value)
{

// create empty variable for each department's time
$deptName = $value."Today"; // set the varaible name
$$deptName = " "; // assign the value to variable

setTime($value); // set time for each department
}


function setTime($deptName)
{
  //$GLOBALS['deptName']= $deptName;
  
  $weekDay = date('l');


if ($weekDay == 'Monday' || $weekDay == 'Tuesday' || $weekDay == 'Wednesday' || $weekDay == 'Thursday' || $weekDay == 'Friday') {
  $hoursPrefix = $weekDay .' Hours: ';
  $weekDay = strToLower($weekDay);

// try catch block for error handling, if some error occurs while executing database queries then the catch block will get executed and error message will be printed out.

 try
 { // try block begins


  $Msg = db_query("SELECT field_".$deptName."_" . $weekDay . "_msg_value FROM {field_data_field_".$deptName."_" . $weekDay. "_msg}")->fetchField();
$Msg = htmlspecialchars($Msg); // to prevent cross-site scripting(XSS)
$MsgTest = trim($Msg);
  if(!empty($MsgTest))
  {
variable_set($deptName.'Today',$Msg);	
  }
  else
  {
  $Open = db_query("SELECT field_".$deptName."_" . $weekDay . "_open_value FROM {field_data_field_".$deptName."_" . $weekDay. "_open}")->fetchField();
  $Close = db_query("SELECT field_".$deptName."_" . $weekDay . "_close_value FROM {field_data_field_".$deptName."_" . $weekDay . "_close}")->fetchField();
  $hoursString = $hoursPrefix . $Open . "am - " . $Close . "pm";
   if ($Open > 0 && $Close > 0) {
     variable_set($deptName.'Today', $hoursString);
   }
   else {
     variable_set($deptName.'Today', 'please check with SCRC for available hours');
   }
  }


 } //try block ends

 catch(Exception $e)
 {
variable_set($deptName.'Today','OOPS!! There seems to be some problem, please contact SCRC for open hours'); //
 }
}


elseif ($weekDay == 'Saturday') {

  $hoursPrefix = $weekDay.' Hours: ';
  //$Open = db_query("SELECT field_scrc_saturday_open_value FROM {field_data_field_scrc_saturday_open}")->fetchField();
  //$Close = db_query("SELECT field_scrc_saturday_close_value FROM {field_data_field_scrc_saturday_close}")->fetchField();
  $hoursString = $hoursPrefix . "by appointment only";
  variable_set($deptName.'Today', $hoursString);
}
elseif ($weekDay == 'Sunday') {
  $hoursPrefix = $weekDay. ' Hours: ';
  //$Open = db_query("SELECT field_scrc_sunday_open_value FROM {field_data_field_scrc_sunday_open}")->fetchField();
  //$Close = db_query("SELECT field_scrc_sunday_close_value FROM {field_data_field_scrc_sunday_close}")->fetchField();
  $hoursString = $hoursPrefix . "(closed)";
  variable_set($deptName.'Today', $hoursString);
}
else {
  $hoursString = '(please contact SCRC for open hours)';
  variable_set($deptName.'Today', $hoursString);

}


} //end of setTime



/* creating blocks for Drupal, starting with SCRC */

/**
* Implements hook_block_info().
*/

function library_hours_block_info() {

        $depts = $GLOBALS['constant'];

      foreach($depts as $values)
{
$deptName = $values;
$blocks[$deptName.'_hours_from_mod'] = array(
                'info' => t($deptName.' Hours from Library Hours Module'),
        );
}
           return $blocks;	

}

/**
* Implements hook_block_view().
*/

function library_hours_block_view($delta = '') {
  
        $depts = $GLOBALS['constant'];
      
        $deptName = explode('_hours_from_mod',$delta); // extracting deptname from the delta string
        $delta = $deptName[0];

$block = array();
        // vars for SCRC hours string (block content)
        $todayString = variable_get($delta.'Today','');
        $deptString = "<p>" . $todayString . "</p>";
// end vars

          if (in_array($delta,$depts))
          {
$subject = $delta.' Hours';
               $block['subject'] = t($subject);
               $block['title'] = $subject;
               $block['content'] = $deptString;
          }
          else
{
               $block['content'] = t('No content for this block');

}

       return $block;
}

require_once 'library_hours.admin.inc';
